import Footer from "../Footer/index";
import Head from "next/head";
import Header from "../Header/index";
const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title} | Digitalxtwin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default Layout;
